name: PR Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - litellm_internal_staging

permissions:
  contents: read

concurrency:
  group: pr-checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    permissions:
      contents: read
    uses: ./.github/workflows/checks.yml
